import type { Metadata } from 'next'
import { Inter, Roboto } from 'next/font/google'
import Nav from '@/components/Header'
import './globals.css'
import Footer from '@/components/Footer'

const roboto = Roboto({
  weight: '400',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Roberto Lopez | Ingeniero en Sistemas y desarrollador',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <div className='flex flex-col min-h-screen'>
          <Nav />
          <main className='app flex-grow'>
            {children}
          </main>
          <Footer />
        </div>
      </body>
    </html>
  )
}
